service: serverless-udagram-app

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  # TODO: Add a function definition
  getGroups:
    handler: src/lambda/http/getGroups.handler
    events:
      - http:
          path: groups
          method: get